name: deepbee
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
    - opencv-python==4.10.0.84
    - numpy==2.1.0
    - matplotlib==3.9.2
    - tqdm==4.66.5
    - keras==3.5.0
    - scikit_image==0.24.0

